#############################################################################
# Makefile for building: Griddler
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue Oct 14 09:53:25 2014
# Project:  griddler.pro
# Template: app
# Command: /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/bin/qmake -spec /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/linux-g++ CONFIG+=debug -o Makefile griddler.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -std=c++11 -fopenmp -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -fopenmp -g -Wall -W $(DEFINES)
INCPATH       = -I/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -std=c++11 -fopenmp -Wl,-rpath,/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/lib
LIBS          = $(SUBLIBS)   -lm 
AR            = ar cqs
RANLIB        = 
QMAKE         = /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/unix.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/linux.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/gcc-base.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/gcc-base-unix.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/g++-base.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/g++-unix.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/qconfig.pri \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/qt_functions.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/qt_config.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/exclusive_builds.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/default_pre.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/debug.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/default_post.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/static.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/unix/gdb_dwarf_index.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/warn_on.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/resources.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/uic.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/yacc.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/lex.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/include_source_dir.prf \
		griddler.pro
QMAKE_TARGET  = Griddler
DESTDIR       = 
TARGET        = Griddler

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: griddler.pro  /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/linux-g++/qmake.conf /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/unix.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/linux.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/gcc-base.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/gcc-base-unix.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/g++-base.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/g++-unix.conf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/qconfig.pri \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/qt_functions.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/qt_config.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/exclusive_builds.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/default_pre.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/debug.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/default_post.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/static.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/unix/gdb_dwarf_index.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/warn_on.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/resources.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/uic.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/yacc.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/lex.prf \
		/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/linux-g++ CONFIG+=debug -o Makefile griddler.pro
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/unix.conf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/linux.conf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/gcc-base.conf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/gcc-base-unix.conf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/g++-base.conf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/common/g++-unix.conf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/qconfig.pri:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/qt_functions.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/qt_config.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/exclusive_builds.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/default_pre.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/debug.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/default_post.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/static.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/unix/gdb_dwarf_index.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/warn_on.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/resources.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/uic.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/yacc.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/lex.prf:
/p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /p/sms/opt2/shared/Qt-4.8.6_static_gcc4.8.2/install/mkspecs/linux-g++ CONFIG+=debug -o Makefile griddler.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Griddler1.0.0 || $(MKDIR) .tmp/Griddler1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Griddler1.0.0/ && (cd `dirname .tmp/Griddler1.0.0` && $(TAR) Griddler1.0.0.tar Griddler1.0.0 && $(COMPRESS) Griddler1.0.0.tar) && $(MOVE) `dirname .tmp/Griddler1.0.0`/Griddler1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Griddler1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

